### ISSUE TITLE
Inconsistent color rendering on macbook

### ISSUE THREAD

**Issue by jkpage00** [kepano/flexoki-obsidian#2]
I really love this color pallete, but I'm finding that my macbook struggles to consistently render the background color. It wavers between the pleasantly warm and creamy paper color, and something whiter and cooler. It's probably an issue with my computer not handling the background color well and not a bug in the theme itself, but curious if you have any suggestions for color/display settings to resolve. I've not seen anything like that inconsistency of color outside of the flexoki color theme in both obsidian and vs code. So maybe its an Electron issue?

**Comment by kepano** [comment]
The colors are directly taken from the original specification. My suggestion would be to look into your settings for True Tone and Night Shift. However this is outside the scope of this theme.

**Comment by jkpage00** [comment]
Thanks for the response, I'll try that
