### ISSUE TITLE
⭐ FEATURE: Follow Obsidian color accent

### ISSUE THREAD

**Issue by Rikiub** [kepano/flexoki-obsidian#3]
_**First**, I love this theme! My eyes appreciate it._

**Second**, It's confusing see this image and not see **"extra colors"** on the theme.

![image](https://raw.githubusercontent.com/kepano/flexoki-obsidian/main/cover.png)

There is only the green color accent, and you cannot change from built-in Obsidian color picker.
I would like could change the accent color!

**Comment by kepano** [comment]
Fixed in 1.1.0
